services:
  hardhat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tokenizeart_hardhat
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
